# ===== Build stage =====
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY CreditPro.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet build -c Release -o /app/build

# ===== Publish stage =====
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# ===== Runtime =====
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CreditPro.dll"]
